### ISSUE TITLE
username / password authentication is deprecated

### ISSUE THREAD

**Issue by johnsturgeon** [howartp84/TeslaControl#2]
Getting the errors:
```
   Tesla EV Control Error          plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Trigger                         Indoor AQ Changes
   Tesla EV Control                Fetching vehicles...
   Disabling plugin "Tesla EV Control 1.0.19"
   Stopping plugin "Tesla EV Control 1.0.19" (pid 17862)
   Tesla EV Control Debug          Token expired - renewing oauth token for 44 days...
   Tesla EV Control Debug          Pre-JSON: {"response":"endpoint_deprecated:_please_update_your_app."}
   Tesla EV Control Error          'created_at'
   Tesla EV Control Error          Error creating connection
   Tesla EV Control Error          Plugin version: 1.0.19
   Tesla EV Control Debug          Traceback (most recent call last):
  File "plugin.py", line 139, in getVehicles
    connection = teslajson.Connection(self.pluginPrefs['username'],self.pluginPrefs['password'])
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Tesla Control.indigoPlugin/Contents/Server Plugin/teslajson.py", line 68, in __init__
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Tesla Control.indigoPlugin/Contents/Server Plugin/teslajson.py", line 74, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/Plugins/Tesla Control.indigoPlugin/Contents/Server Plugin/teslajson.py", line 82, in post
KeyError: 'created_at'

   Tesla EV Control Error          Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 435, in runConcurrentThread
  File "plugin.py", line 146, in getVehicles
UnboundLocalError: local variable 'connection' referenced before assignment
```

Tesla updated to OAuth, this plugin needs to as well

**Comment by howartp84** [comment]
Resolved in Versions 3.0.0 and beyond, rewritten in Python3
